Food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    path("", views.ping, name="ping"),
    path("index/", views.HomeView.as_view(), name="index"),
    path("<int:Item_id>/", views.detail_view, name="detail_view"),
    path("add/", views.add_item, name="add_item"),
    path("update/<int:Item_id>/", views.update_item, name="update_item"),
    path("delete/<int:Item_id>/", views.delete_item, name="delete_item"),
]

FoodApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("Food.urls")),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("register/", views.user_register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

Food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=100)
    item_price = models.IntegerField()
    item_desc = models.TextField()
    item_img = models.ImageField(upload_to="", default="default_image.png")

    def __str__(self):
        return self.item_name

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        default="profile_pics/profile_pic.png", upload_to="profile_pics/"
    )
    location = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} Profile"

Food/forms.py
from django import forms
from .models import Item


class itemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_name", "item_price", "item_desc", "item_img"]

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_texts = {field: "" for field in fields}

Food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from .forms import itemForm
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required

# Create your views here.


def ping(request):
    return HttpResponse("pong")


# def home(request):
#     query_set = Item.objects.all()
#     context = {"items": query_set}
#     return render(request, "food/index.html", context)


class HomeView(ListView):
    model = Item  # This is the model that the view will be working with
    template_name = "food/index.html"
    context_object_name = "items"

    # def get_queryset(self):
    #     # Return a custom queryset
    #     return Item.objects.all()


def detail_view(request, Item_id):
    query_set = Item.objects.get(pk=Item_id)
    context = {"Item": query_set}
    return render(request, "food/detail_view.html", context)


@login_required
def add_item(request):
    if request.method == "POST":
        form = itemForm(request.POST, request.FILES)
        if form.is_valid():
            Item = form.save(commit=False)
            Item.user_name = request.user
            Item.save()
            return redirect("food:index")

    else:
        form = itemForm()
    return render(request, "Food/create_Item.html", {"form": form})


def update_item(request, Item_id):
    instance = Item.objects.get(pk=Item_id)
    form = itemForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "Food/create_Item.html", {"form": form, "Item": instance})


def delete_item(request, Item_id):
    instance = get_object_or_404(Item, pk=Item_id)
    if request.method == "POST":
        instance.delete()
        return redirect("food:index")
    return render(request, "Food/delete_Item.html", {"Item": instance})

users/views.py
from django.shortcuts import render
from .forms import UserRegisterForm
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth import logout

# Create your views here.


def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            form.save()
            messages.success(
                request, f"Welcome {username}, Account has been  successfully created"
            )
            return redirect("login")
    else:
        form = UserRegisterForm()

    return render(request, "users/registration.html", {"form": form})


def user_logout(request):
    logout(request)
    return render(request, "users/logout.html")


def profile(request):
    return render(request, "users/profile.html")

Food/templates/Food/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'food/style.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Food Menu</title>
</head>

<body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid ">
            <a href="{% url 'food:index' %}" class="navbar-brand">FoodAPP</a>
            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:add_item' %}">Add Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Delete Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">View Item</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock content %}


</body>

Food/templates/Food/create_item.html
{% extends "Food/base.html" %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100"> <!-- Full screen centering -->
    <div class="row w-100 justify-content-center">
        <div class="col-md-4"> <!-- Adjust width of the card -->
            <div class="card">
                <div class="card-header text-white bg-dark text-center">
                    <div class="card-title mb-0">
                        Add or update Item
                    </div>
                </div>
                <div class="card-body">
                    <form
                        action='{% if Item %}{% url "food:update_item" Item.id %}{% else %}{% url "food:add_item" %}{% endif %}'
                        method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-dark">
                            {% if Item %}
                            Update Item
                            {% else %}
                            Add Item
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}




<!-- <form action='{% if item %}{% url "food:update_item" item.id %}{% else %}{% url "food:add_item" %}{% endif %}'
    method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark">
        {% if item %}
        Update Item
        {% else %}
        Add Item
        {% endif %}
    </button>
</form> -->

Food/templates/Food/delete_item.html
<form action="{% url 'food:delete_item' Item.id %}" method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{Item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

Food/templates/Food/detail_view.html
{% extends 'Food/base.html' %}
{% block content %}

<div class="row">

    <div class="col-md-6">
        <img src="{{Item.item_img.url}}" alt="{{item.item_name}}" class="img-fluid w-100">
    </div>
    <div class="col-md-6">
        <h2>{{Item.item_name}}</h2>
        <p>{{Item.item_desc}}</p>
        <p>{{Item.item_price}}$</p>
        <p>{{Item.user_name.username}}</p>
        <a href="{% url 'food:delete_item' Item.id %}" class="btn btn-danger">Delete</a>
    </div>
</div>

<!-- <h2>{{item.item_name}}</h2>
<p>{{item.item_desc}}</p>
<p>{{item.item_price}}$</p> -->
{% endblock content %}

Food/templates/Food/index.html
{% extends "Food/base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        {% for item in items %}
            <!-- Each card takes 6 columns (half of the row), so 2 cards will fit per row -->
            <div class="col-md-6 mb-4">
                <div class="card h-100">
                    <img src="{{ item.item_img.url }}" style="width: 300px; height: 200px; object-fit: cover;" class="card-img-top" alt="{{ item.item_name }}">

                    <div class="card-body">
                        <h5 class="card-title">{{ item.item_name }}</h5>
                        <p class="card-text">{{ item.item_desc }}</p>
                        <p class="card-text">{{ item.item_price }}$</p>
                        <p class="card-text">{{ item.user_name.username }}</p>
                        <a href="{% url 'food:detail_view' item.id %}" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

users/templates/users/login.html
{% extends "Food/base.html" %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100"> <!-- Full screen centering -->
    <div class="row w-100 justify-content-center">
        <div class="col-md-4"> <!-- Adjust width of the card -->
            <div class="card">
                <div class="card-header text-white bg-dark text-center">
                    <div class="card-title mb-0">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-dark w-100 mt-3">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}











<!-- <h2>Login</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
</form> -->

users/templates/users/logout.html
<h1>You have been logged out! </h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="No image found" height="200px">

users/templates/users/registration.html
{% extends "Food/base.html" %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center vh-100"> <!-- Full screen centering -->
    <div class="row w-100 justify-content-center">
        <div class="col-md-4"> <!-- Adjust width of the card -->
            <div class="card">
                <div class="card-header text-white bg-dark text-center">
                    <div class="card-title mb-0">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}

                        <button type="submit" class="btn btn-dark w-100 mt-3">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

    {% comment %} <form action = "{% url 'register' %}" method="post">
        {% csrf_token %}
        <h1>Registration</h1>
        {{form.as_p}}
        <button type="submit">Sign up</button>
    </form> {% endcomment %}
    
    

{% endblock content %}